MERGE DEV TO MAIN
kumoh42/futsal-server pull request #101
Opened 2024-03-29 12:23 UTC by badasskim

2024-03-30 15:09 UTC, Journeybonbon requested changes

2024-03-30 15:09 UTC, Journeybonbon commented on src/reservation/time/reservation-time.service.ts
> +    const cronFormat = `0 55 ${hour} ${day}`;
서버 시간 원래대로 돌아온거면 55분이 아닌 정각에 맞춰줘야합니다!

2024-03-31 20:36 UTC, badasskim commented on src/reservation/time/reservation-time.service.ts
> +    const cronFormat = `0 55 ${hour} ${day}`;
앗 넵 수정하였습니다 !

2024-04-01 05:50 UTC, Journeybonbon approved these changes
팀장 최고 ~

2024-04-02 05:18 UTC, Hyunoi approved these changes

2024-04-02 05:25 UTC, Juhye0k approved these changes

2024-04-02 11:26 UTC, ajb3296 approved these changes

2024-04-04 13:46 UTC, merged