ADD: slack api connection
kumoh42/futsal-server pull request #28
Opened 2023-08-13 13:48 UTC by badasskim

+ slack webhook api를 사용하여 문의사항을 슬랙 메시지로 확인 할 수 있습니다.
+ request : axios 사용

2023-08-14 01:01 UTC, gimseonjin commented on src/inquiry/inquiry.module.ts
> +export class InquriyModule {}
개인적으로 Inquriy 보다는 Slack Module 이라는 이름이 더 어울릴 거 같아요!!

2023-08-14 01:08 UTC, gimseonjin requested changes

2023-08-14 01:08 UTC, gimseonjin commented on src/inquiry/inquiry.controller.ts
> +    async temp(@Body() body: { name: string, text: string }, @Res() response: Response) {
이거 DTO로 만들어줘요!

2023-08-14 01:08 UTC, gimseonjin commented on src/inquiry/inquiry.controller.ts
> +      response.status(200).json({ message: ['send 성공'] });
@Res() response 가져와서 반환하지 말고

return {message: 'send 성공'}

이런 식으로 해줘요

2023-08-14 01:08 UTC, gimseonjin commented on src/inquiry/inquiry.service.ts
> +    private readonly slcakWebhookUrl = process.env.SLACK_URL;
이거 대문자!! SLACK_WEB_HOOK_URL

2023-08-14 01:08 UTC, gimseonjin commented on src/inquiry/inquiry.service.ts
> +        const nowTime = format(new Date(), 'yyyy-MM-dd HH:MM:SS');
이거 dayjs 쓰는 걸로 수정해줘요

2023-08-14 01:08 UTC, gimseonjin commented on src/inquiry/inquiry.service.ts
> +            `----------\n사용자 : ${name}\n내용: ${text}\n시간: ${nowTime}\n----------`
이거 하드 코딩말고 .env나 db로 옮겨줘요!

가능하면 env

2023-08-14 01:08 UTC, gimseonjin commented on src/inquiry/inquiry.service.ts
> +        if (   name === undefined
여기 level에서 하지말고 dto 만들어서 거기서 해줘요

2023-08-14 06:21 UTC, Journeybongbong approved these changes
이미 선진선배가 콕콕 다 말씀해주셨군요!!
LGTM !

2023-08-15 09:12 UTC, badasskim commented on src/inquiry/inquiry.service.ts
> +            `----------\n사용자 : ${name}\n내용: ${text}\n시간: ${nowTime}\n----------`
이해를 잘 못해서 그런데 혹시 env에 옮기라는 뜻이 정확히 어떤건지 여쭤 볼 수 있을까요 .. ?
env에다가 저 문자열을 가져와서 사용하라는 뜻인 거인가요 ?

2023-08-15 11:32 UTC, gimseonjin commented on src/inquiry/inquiry.service.ts
> +            `----------\n사용자 : ${name}\n내용: ${text}\n시간: ${nowTime}\n----------`
응응!!! 뭐 예를 들면  const msgTemplate = env.process.MSG 이런느낌?

그리고 .replace나 replaveAll 쓰면 될 거 같애

2023-08-15 13:05 UTC, badasskim commented on src/inquiry/inquiry.service.ts
> +            `----------\n사용자 : ${name}\n내용: ${text}\n시간: ${nowTime}\n----------`
해결했습니다

2023-08-15 13:19 UTC, gimseonjin requested changes

2023-08-15 13:19 UTC, gimseonjin commented on src/inquiry/inquiry.controller.ts
> +      await this.inquiryService.sendSlackMessage(user.userName, user.userId,  inquriyMessageDto.email, inquriyMessageDto.text, );
이거 구조 분해 사용해주세요!!

예를 들면

`const { email, text } = inqurityMessageDto`

이런식으로

2023-08-15 13:19 UTC, gimseonjin commented on src/inquiry/inquiry.service.ts
> +        let nowTime = dayjs().format("YYYY.MM.DD HH:mm:ss");
no let yes const

둘의 차이점을 공부해오시오!!

2023-08-15 13:19 UTC, gimseonjin commented on .github/workflows/deploy.yml
> +
여기에 msg template 추가해주세용

2023-08-15 14:41 UTC, badasskim commented on src/inquiry/inquiry.service.ts
> +        let nowTime = dayjs().format("YYYY.MM.DD HH:mm:ss");
변수와 상수... ㅠㅠ

2023-08-15 15:42 UTC, gimseonjin approved these changes
LGTM

2023-08-16 01:15 UTC, merged