사전예약 시간 설정
kumoh42/futsal-server pull request #57
Opened 2023-09-05 06:10 UTC by Hyunoi

- 사전 예약을 시작하는 시간 예약 기능을 만들었습니다.
- 사전 예약 시간이 되어 새로고침 시 현재 진행되고 있는 예약을 조회하도록 했습니다.
- 사전 예약을 재개, 중단하는 기능과 사전예약 내역을 초기화하는 기능을 만들었습니다.

2023-09-05 13:53 UTC, badasskim approved these changes
lgtm

2023-09-08 11:47 UTC, gimseonjin commented on src/reservation/reservation.controller.ts
> +  @Put('/pre/stop')
/pre/ 머시기

가 너무 많네요!

쿼리 스트링이나 파람을 사용해서 줄여볼 수 있을 거 같은데 한번 시도해보겠습니까?

2023-09-08 11:48 UTC, gimseonjin commented on src/reservation/reservation.controller.ts
> +  @Put('/pre/stop')
그리고 api operation도 없는거 같아요!

2023-09-08 11:50 UTC, gimseonjin commented on src/reservation/reservation.service.ts
> +    else if (this.PreReservationList.length == 0 && this.NowSet.length !== 0) {
이게... 왜 비어있는거에요???

살짝 코드 이쁘게 고칠 수 있을 거 같은데

2023-09-08 11:51 UTC, gimseonjin commented on src/reservation/reservation.service.ts
> +      const dateCompare = a.date.localeCompare(b.date)
이거 dayjs의 날짜 비교 로직으로 수정해주세요!
그거 쓰면 아마 날짜 & 시간 바로 비교할 수 있을거에ㅛ

2023-09-08 11:53 UTC, gimseonjin requested changes
흠!! 날잡고 리펙토링 같이 합시다!

2023-09-08 11:53 UTC, gimseonjin commented on src/reservation/reservation.service.ts
> +    for (let i = 0; i < this.PreReservationList.length; i++) {
이거 코드를 class 내부의 상태로 사용하는거 같은데 외부 파라미터로 받아오는 방식으로 수정해주세요!!

이런 식으로 구현하면 코드 읽기도 어렵고, 어떤 기능인지 이해하기가 조금 어렵네요!

2023-09-10 07:56 UTC, closed without merging