Kum 113 예약막기
kumoh42/futsal-server pull request #59
Opened 2023-09-12 12:45 UTC by badasskim

+ 예약을 블락하는 기능을 추가했습니다.
+ 다만 생성된 레코드에 값들을 추가하는 것, 아니면 기존 레코드를 덮어쓰기( update ) 때문에 예약 시작 전 예약막기예약(?) 있으면 좋겠다는 생각이 들었지만 필수적인 건 아니니 pass 했습니다.
+ 궁금한 게 있는데 혹시 dblock 을 사용한다면 덮어쓰기가 불가능 한데 혹시 관리자 예약 막기에도 다른 처리가 필요한지 궁금합니다..!

2023-09-12 16:43 UTC, 137042 requested changes
1. 블락 기능은 테스트가 끝났다고 들었으니 잘 수행되겠죠? 고생했어요
2. 이게 진짜 무슨 말인지 모르겠습니다.
3. DB Lock이 있어도 덮어쓰기가 Update를 말하는 거라면 순차적으로... 예를 들자면 Queue처럼 처리됩니다.
예약 막기의 경우 관리자가 많지 않고, 동시에 발생할 가능성이 낮기 때문에 우선 넘어갔었죠?
그런데 "예약 막기"라는 트랜잭션이 "SELECT * ~" -> "UPDATE is_able = 'N' ~" 이런 구조라면 SELECT 질의가 다른 트랜잭션에서 날아오면서 문제가 생길 수 있긴 합니다. 그래서 테이블 자체에 적당한 단계의 제한이 필요할 수도 있죠.

2023-09-12 16:43 UTC, 137042 commented on src/common/dto/reservation/block-reservation.dto.ts
> +    return 'startDate는 endDate보다 늦거나 같을 수 없으며,시작일과 종료일은 같은 월에 속해야 합니다. 또한 Time은 2의 배수여야 합니다.';
startDate & endDate 라는 키워드로 오류를 알리고 싶다면 구문이 끝날 때까지 동일하게 사용해주세요 ~
시작일 & 종료일 또는 startDate & endDate 둘 중 하나로 통일하여 메시지 및 주석을 작성하면 혼동을 막아줄 것 같습니다. 특별히 이유가 있다면 수정하지 않고 넘어가도 되고요,

2023-09-12 16:43 UTC, 137042 commented on src/common/dto/reservation/block-reservation.dto.ts
> +    if(new Date(modifiedStartDate) >=new Date(modifiedEndDate)) { return false; }
1. modifiedStartDate가 결국 String인 것 같은데, 그렇다면 상수 선언없이 바로 Date(startDate + ...) 가능한가요?
2. Date 형변환을 위해 제공하는 함수에 time이 누락되면 알아서 처리하는 함수가 없나요?
3. 1, 2 방법이 가능하지만 가독성을 높이기 위해 이렇게 작성했나요?

충분한 검증이 있으므로 별 문제가 없을 것으로 예상되나, 방법을 한 번 찾아보는 것도 좋을 듯 하네요.

2023-09-12 16:43 UTC, 137042 commented on src/reservation/reseravtion-block.ts
> +        //일단 startDate랑 endDate 둘 다 사전, 정식 예약 테이블이 존재하는 지 검색하여야 하는데
개발한 함수 등에 대해 풀이용 주석을 적는 것은 본인의 스타일 차이입니다.
그렇지만 개선할 사항에 대해서 주석을 적는 것은 습관이 될까봐 살짝 걱정되네요.

ts 및 vscode에도 TODO가 있을 겁니다. 인식이 안되면 extension 설치를 권장합니다.
발생할 것으로 예상되는 문제가 있다면 아래처럼 처리하는 것이 적합해 보입니다.
- 팀원들과 공유해야 하는 경우에는 급하면 메신저 등으로 즉시 공유
- 단순 개선 사항으로 판단되는 경우 회의에서 공유
- 혼자 고민해야 할 부분이라고 판단했다면 TODO에 "할 일"을 간략하게 기재

2023-09-12 16:43 UTC, 137042 commented on src/reservation/reseravtion-block.ts
> +            member_srl: 1,
추후 srl이 auto increment로 설정된 DB로 변경했을 때 문제가 될 수 있습니다.
관리자의 강제 점유... 와 같은 서비스 상의 예외로 만들고 싶다면 다른 값을 권장합니다.
가령, 지금은 srl이 숫자고 모든 값이 양수라면 -1로 초기화를 시켜도 괜찮겠네요.
그렇지만 srl이 어떻게 생성되는 id값인지 파악되지 않은 상황이죠?
문제가 생길 수도 있고 아닐 수도 있다... 정도로 알고 있기만 해도 될 것 같습니다.

+) 동일한 값 초기화가 반복되니 위에서 해당 값을 미리 상수 선언할 수 있는지 알아봅시다.

2023-09-14 11:54 UTC, badasskim commented on src/common/dto/reservation/block-reservation.dto.ts
> +    if(new Date(modifiedStartDate) >=new Date(modifiedEndDate)) { return false; }
1. 가능합니다 ! 다만 3번과 같이 기존 변수에다가 이것저것 붙이는 것은 좋지 않다고 생각해서 따로 상수로 빼두고 작업했습니다.
(사실 엄격히 따지고 보면 위에
    1.  time이 2의 배수인지
    2. 시작일과 마감일이 같은 월에 속해있는지 확인하는 코드
        들 역시 변수로 분리하는 것이 맞지만 어느정도 알아볼 수 있는 선에서 작성하게 되었습니다.)
돌이켜보니 컨셉을 한 가지로 유지하지 못 하고 우유부단하게 짰던 거 같네요. 다음 부터는 확실하게 작성해보겠습니다.

2. 네 제가 찾아봤을 때는 '시간'을 포함한 문자열에는 나머지 time을 추가해주는 거는 없었던 거 같습니다. 
기존 방법 이외에 것을 생각했을 때는 만약 "2023-08-20T10" 이라는 문자열을 Date 객체로 생성하려고 하면 "T10" 부분을 스플릿하고 객체 생성 후("2023-08-20"으로 생성시 자동으로 time을 생성해줍니다. ), 입력된 타임을 따로 추가하는 걸 고려해봤지만, 사실 그렇게 좋은 방법은 아니였던 것 같습니다.

3. 구현당시에는 이 방법밖에는 없다고 생각했었습니다.

+++ 사실 api 명세를 정할 당시에 요청바디를 time까지 다 받는 거는 "굳이? 시간 빼고는 다 0일텐데 그냥 나머지 떨구고 TXX 까지만 받죠 ?" 라고 얘기하고 합의했었는데, 지금과 구현 도중에 후회를 많이 했습니다. ~~(정현님 죄송합니다)~~

2023-09-14 12:05 UTC, badasskim commented on src/reservation/reseravtion-block.ts
> +        //일단 startDate랑 endDate 둘 다 사전, 정식 예약 테이블이 존재하는 지 검색하여야 하는데
아 명백히 저의 실수네요, 코드 명세같은 거는 괜찮지만 본인이 해야 할 것 ! 은 적으면 안 되는 거였군뇨
수정하겠습니다 !

2023-09-14 12:15 UTC, badasskim commented on src/reservation/reseravtion-block.ts
> +            member_srl: 1,
member_srl을 -1로 줘도 잘 삽입이 되네요 ! 수정하겠습니다 감사합니다 !!

2023-09-14 12:15 UTC, badasskim commented on src/common/dto/reservation/block-reservation.dto.ts
> +    return 'startDate는 endDate보다 늦거나 같을 수 없으며,시작일과 종료일은 같은 월에 속해야 합니다. 또한 Time은 2의 배수여야 합니다.';
넵 수정하겠습니다 !

2023-09-14 12:16 UTC, badasskim commented on src/reservation/reseravtion-block.ts
> +            member_srl: 1,
너무 자세한 피드백 감사합니다.... 감동 받았읍니다 진짜로...ㅠㅠㅠ
다시 커밋하고 pr 올리겠습니다 !

2023-09-18 03:27 UTC, 137042 approved these changes
Looks good to me.

2023-09-18 12:26 UTC, merged