로그인 기능 구현
kumoh42/futsal-server pull request #7
Opened 2023-07-28 09:53 UTC by badasskim

로그인 기능을 구현했습니다 !

+ api 명세서 : 금오사이 기술팀 명세서 참조
+ jwt를 통한 토큰 auth 구현(AT,RT)

2023-08-03 11:38 UTC, gimseonjin requested changes

2023-08-03 11:38 UTC, gimseonjin commented on package.json
> +    "passport-local": "^1.0.0",
우리 이제 passport 안 쓰니까 이거 지워주세요!!

2023-08-03 11:38 UTC, gimseonjin commented on src/common/decorators/user.decorator.ts
> +    const {userId, userName} = ctx.switchToHttp().getRequest().user.userId
어 이거 내가 잘못했다

`ctx.switchToHttp().getRequest().user`

해야 동작할 거 같습니다

2023-08-03 11:38 UTC, gimseonjin commented on src/auth/dto/cleate-user.dto.ts
> +export class CreateUserDto {
여기 비밀번호 제한 조건까지 추가해서 pr 올려주세요!!

2023-08-03 11:39 UTC, badasskim commented on src/auth/dto/cleate-user.dto.ts
> +export class CreateUserDto {
엇 네 알겠습니다 !

2023-08-04 11:59 UTC, Hyunoi commented on src/entites/xe_reservation.entity.ts
> +  is_holyday: string;
is_holy -> is_holiday
regdatge  -> regdate
이렇게 변수명 바꿔야 돼요!

2023-08-04 12:02 UTC, Hyunoi approved these changes
lgtm!

2023-08-04 12:02 UTC, Hyunoi commented on src/entites/xe_reservation_pre.entity.ts
> +  is_holyday: string;
is_holy -> is_holiday
regdatge -> regdate
이렇게 변수명 바꿔야 돼요!

2023-08-04 12:11 UTC, badasskim commented on src/entites/xe_reservation_pre.entity.ts
> +  is_holyday: string;
넵 수정했습니당~

2023-08-04 12:18 UTC, 137042 commented on src/auth/dto/cleate-user.dto.ts
> +export class CreateUserDto {
"cleate" ?

2023-08-04 12:21 UTC, 137042 requested changes

2023-08-04 12:21 UTC, 137042 commented on src/auth/dto/cleate-user.dto.ts
파일명 수정해주세요 ~

2023-08-04 13:33 UTC, badasskim commented on src/auth/dto/cleate-user.dto.ts
완료 !

2023-08-04 13:33 UTC, 137042 approved these changes

2023-08-04 13:35 UTC, Journeybongbong approved these changes
LGTM!

2023-08-04 13:37 UTC, badasskim commented on src/user/user.controller.ts
> +    return this.userService.getUserInfo(user.userId);
수정 했습니다!~!~

2023-08-04 13:38 UTC, merged